training:
  loss_function:
    name: CrossEntropyLoss # или NLLLoss, HingeEmbeddingLoss
    params: {}
  optimizer:
    name: Adam
    params:
      lr: 0.001
  num_epochs: 5
  batch_size: 64
  k_folds: 5
  model:
    type: 'resnet'  # или 'efficientnet'
    version: 'resnet18'  # или 'b0', 'b1', 'b2', 'b3', 'resnet18', 'resnet34', 'resnet50'
    num_classes: 2