training:
  loss_function:
    name: CrossEntropyLoss
    params: {}
  optimizer:
    name: Adam
    params:
      lr: 0.001
  num_epochs: 5
  batch_size: 64
  k_folds: 5
  model:
    num_classes: 2